// lib/src/features/community/dummy_posts.dart

import 'data/post_model.dart';

final List<Post> dummyPosts = [
  Post(
    id: '1',
    category: 'review',
    title: '서울 뮤지컬 라이온킹 관람 후기',
    content: '웅장한 무대와 음악이 압권이었습니다. 모두가 즐길 수 있는 최고의 공연!',
    author: '관람객1',
    region: '서울',
    genre: '뮤지컬/오페라',
    views: 120,
    likes: 45,
    date: DateTime(2025, 10, 15, 10, 30),
    performanceId: 'performance:12345',
    performanceTitle: '뮤지컬 라이온킹',
    performanceUrl: 'https://example.com/lionking',
  ),
  Post(
    id: '2',
    category: 'friend',
    title: '부산 전시회 같이 갈 친구 찾아요!',
    content: '평일에 벡스코에서 하는 현대 미술 전시회 같이 보실 분 구합니다.',
    author: '친구찾기달인',
    region: '부산',
    genre: '전시',
    views: 80,
    likes: 12,
    date: DateTime(2025, 10, 14, 15, 0),
    performanceId: 'performance:67890',
    performanceTitle: '현대 미술의 흐름',
    performanceUrl: null,
  ),
  Post(
    id: '3',
    category: 'review',
    title: '광주 국악 한마당 솔직 후기 - 조금 아쉬웠던 점',
    content: '전통 국악의 아름다움을 느낄 수 있었지만, 음향 시설이 조금 아쉬웠습니다.',
    author: '국악사랑',
    region: '광주',
    genre: '국악',
    views: 200,
    likes: 55,
    date: DateTime(2025, 10, 13, 11, 45),
    performanceId: 'performance:11223',
    performanceTitle: '2025 광주 국악 한마당 축제',
    performanceUrl: 'https://example.com/gukak',
  ),
  Post(
    id: '4',
    category: 'friend',
    title: '서울 콘서트 같이 갈 동행 구합니다!',
    content: '아이유 콘서트 양일 모두 가는 분, 끝나고 후기 같이 나눌 분 찾아요!',
    author: '아이유팬',
    region: '서울',
    genre: '음악/콘서트',
    views: 350,
    likes: 90,
    date: DateTime(2025, 10, 12, 19, 20),
    performanceId: 'performance:44556',
    performanceTitle: '아이유 콘서트 The Golden Hour',
    performanceUrl: 'https://example.com/iu_concert',
  ),
  Post(
    id: '5',
    category: 'review',
    title: '경남 연극 소극장 공연 후기',
    content: '배우들의 열연이 돋보였던 감동적인 연극이었습니다.',
    author: '연극홀릭',
    region: '경남',
    genre: '연극',
    views: 60,
    likes: 5,
    date: DateTime(2025, 10, 11, 22, 10),
    performanceId: 'performance:77889',
    performanceTitle: '소극장 연극: 기억의 조각',
    performanceUrl: 'https://example.com/play',
  ),
  // Pagination 테스트를 위한 추가 더미 데이터
  Post(
    id: '6',
    category: 'review',
    title: '대구 무용/발레 공연 감상평',
    content: '아름다운 발레 동작에 넋을 잃었습니다.',
    author: '발레마니아',
    region: '대구',
    genre: '무용/발레',
    views: 15,
    likes: 3,
    date: DateTime(2025, 10, 10, 09, 0),
  ),
];